---

- hosts: all
  tasks:

- name: Apply common configuration
  hosts: all
  user: asadmin
  become: yes
  become_method: sudo
  tasks:
  roles:
    - common

- name:Install and config webserver
  hosts: webserver
  user: asadmin
  become: yes
  become_method: sudo
  tasks: 
  roles:
    - web 
