---

- name: Install apache package
  yum: name={{ item }} state=present
  with_items:
    - httpd
    - httpd-tools

- name: copy apache index file
  copy: src=index.html dest=/var/www/html/index.html
  tags: apache
  notify: restart apache service

- name: add firewall rule 
  shell: iptables -I INPUT -p tcp --dport http -j ACCEPT -m commnet --comment "Apache port 80"
  tags: apache
- name: Save Ip tables
  command: iptables-save
  tags: apache
